name: Main Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies (Ubuntu/Debian)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          curl \
          git \
          libssl-dev \
          make \
          meson \
          ninja-build \
          wget \
          unzip \
          zlib1g-dev

    - name: Grab, unpack, & install the scratchpkg package
      run: |
        wget https://github.com/venomlinux/scratchpkg/archive/refs/heads/master.zip -O scratchpkg-master.zip
        unzip scratchpkg-master.zip
        cd scratchpkg-master
        chmod +x INSTALL.sh
        sudo ./INSTALL.sh

    - name: Verify scratchpkg installation
      run: |
        scratch installed


