name: Main Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies (Ubuntu/Debian)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          libssl-dev \
          make \
          meson \
          ninja-build \
          scdoc \
          zlib1g-dev

    - name: Grab, unpack, & install the apk-tools-static package
      run: |
        wget https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/apk-tools-static-3.0.0_rc5_git20250715-r0.apk -O apk-tools-static.apk
        mkdir -p apk-tools
        tar -xvf apk-tools-static.apk -C apk-tools --strip-components=1
        sudo mv -v apk-tools/sbin/apk.static /usr/local/sbin/apk
        chmod +x /usr/local/sbin/apk

    - name: Verify apk-tools installation
      run: |
        apk --version

    - name: Remove apk-tools-static package
      run: rm -rfv apk-tools-static.apk apk-tools